---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dtru5625/public_html/
    - /bin/cp -R css /home/dtru5625/sitesavnum
    - /bin/cp -R html /home/dtru5625/sitesavnum
    - /bin/cp -R img /home/dtru5625/sitesavnum
    - /bin/cp -R js /home/dtru5625/sitesavnum
    - /bin/cp -R pdf /home/dtru5625/sitesavnum
    - /bin/cp -R tinymce /home/dtru5625/sitesavnum
    - /bin/cp index.html /home/dtru5625/sitesavnum
